use std::{
    collections::BTreeMap,
    env,
    error::Error,
    fmt::Write as _,
    fs::read_dir,
    io::Write as _,
    path::PathBuf,
    process::{Command, Stdio},
};

fn main() -> Result<(), Box<dyn Error>> {
    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "riscv64".into());
    println!("cargo:rerun-if-changed={arch}.ld");
    println!("cargo:rerun-if-changed=../../userspace/");
    println!("cargo:rerun-if-env-changed=CARGO_CFG_TARGET_ARCH");
    // For unit tests (which produce a binary from this library crate)
    println!("cargo:rustc-link-arg=-Tcrates/kernel/{arch}.ld");

    if is_miri_execution() {
        // Under Miri, the file already exists from a prior build.
        return Ok(());
    }

    generate_userspace_programs_include()?;

    Ok(())
}

/// Where to look for compiled userspace binaries.
///
/// Hardcoded to `<repo>/build/userspace/artifacts`, matching the
/// `binaryDir` pinned by CMakePresets.json. CMake populates this dir via
/// the `userspace-all` target; bare `cargo build` / rust-analyzer pick up
/// whatever a prior CMake build left behind.
fn userspace_artifact_dir() -> PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest).join("../../build/userspace/artifacts")
}

fn is_miri_execution() -> bool {
    env::var_os("CARGO_CFG_MIRI").is_some()
}

fn generate_userspace_programs_include() -> Result<(), Box<dyn Error>> {
    const USERSPACE_PROGRAMS_PATH: &str = "src/autogenerated/userspace_programs.rs";

    let mut content = String::new();

    // Only the unit-test fixtures (INIT, PROG1) are consumed; the rest
    // are embedded for symmetry so the PROGRAMS array stays complete.
    writeln!(content, "#![allow(dead_code)]")?;
    writeln!(content, "use abi::include_bytes_align_as;\n")?;

    // Use BTreeMap to have the program names in a sorted order
    let mut programs: BTreeMap<String, String> = BTreeMap::new();

    let mut canonical_to_static: BTreeMap<PathBuf, String> = BTreeMap::new();

    let dir = userspace_artifact_dir();
    println!("cargo:rerun-if-changed={}", dir.display());
    if dir.exists() {
        for entry in read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            let absolute_path = std::fs::canonicalize(&path)?;
            let original_file_name = path.file_name().unwrap().to_str().unwrap();
            let file_name = original_file_name.to_uppercase().replace('-', "_");

            programs.insert(original_file_name.to_owned(), file_name.clone());

            if let Some(first_static) = canonical_to_static.get(&absolute_path) {
                writeln!(content, "pub static {file_name}: &[u8] = {first_static};")?;
            } else {
                writeln!(
                    content,
                    "pub static {file_name}: &[u8] = include_bytes_align_as!(u64, \"{}\");",
                    absolute_path.to_string_lossy()
                )?;
                canonical_to_static.insert(absolute_path, file_name);
            }
        }
    }

    writeln!(content)?;
    write!(content, "pub static PROGRAMS: &[(&str, &[u8])] = &[")?;
    for (original_file_name, file_name) in programs {
        write!(content, "(\"{original_file_name}\", {file_name}),")?;
    }

    write!(content, "];")?;

    // Format in memory, then only write if content changed — preserves mtime to avoid rebuilds
    let mut rustfmt = Command::new("rustfmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()?;
    rustfmt
        .stdin
        .take()
        .unwrap()
        .write_all(content.as_bytes())?;
    let formatted = String::from_utf8(rustfmt.wait_with_output()?.stdout)?;

    let existing = std::fs::read_to_string(USERSPACE_PROGRAMS_PATH).unwrap_or_default();
    if existing == formatted {
        return Ok(());
    }

    std::fs::write(USERSPACE_PROGRAMS_PATH, &formatted)?;

    Ok(())
}
