use core::ffi::{c_int, c_uint};
use headers::{
    errno::Errno,
    syscall_types::{
        FIONBIO, TCGETS, TCSETS, TCSETSF, TCSETSW, TIOCGPGRP, TIOCGWINSZ, TIOCSPGRP, termios,
    },
};

use crate::{
    autogenerated::userspace_programs::PROGRAMS,
    print, println,
    processes::{
        fd_table::{FdFlags, FileDescriptor},
        process_table,
    },
    syscalls::linux_validator::LinuxUserspaceArg,
};
use common::{
    ioctl::{ARPHRD_ETHER, Ifreq, SIOCGIFHWADDR, SIOCSIFADDR, SOLAYA_LIST_PROGRAMS, SOLAYA_PANIC},
    pid::Tid,
};

use super::linux::{LinuxSyscallHandler, LinuxSyscalls};

impl LinuxSyscallHandler {
    pub(super) fn do_ioctl(&self, fd: c_int, op: c_uint, arg: usize) -> Result<isize, Errno> {
        let descriptor = self
            .current_process
            .with_lock(|p| p.fd_table().get_descriptor(fd))?;

        match descriptor {
            FileDescriptor::Tty(ref device) if op == TIOCGWINSZ => {
                let ptr = LinuxUserspaceArg::<*mut [u16; 4]>::new(arg, self.get_process());
                ptr.write_slice(&[[24, 80, 0, 0]])?;
                Ok(0)
            }
            FileDescriptor::Tty(_) if op == SOLAYA_LIST_PROGRAMS => {
                for (name, _) in PROGRAMS {
                    print!("{name} ");
                }
                println!();
                Ok(0)
            }
            FileDescriptor::Tty(_) if op == SOLAYA_PANIC => {
                panic!("Userspace triggered kernel panic");
            }
            #[cfg(feature = "udp")]
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket if op == FIONBIO => {
                let arg_ptr = LinuxUserspaceArg::<*const c_int>::new(arg, self.get_process());
                let value = arg_ptr.validate_ptr()?;
                let flags = if value != 0 {
                    FdFlags::from_raw(headers::syscall_types::O_NONBLOCK as i32)
                } else {
                    FdFlags::default()
                };
                self.current_process
                    .with_lock(|p| p.fd_table().set_flags(fd, flags))?;
                Ok(0)
            }
            #[cfg(feature = "udp")]
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket
                if op == SIOCGIFHWADDR =>
            {
                if !crate::net::has_network_device() {
                    return Err(Errno::ENODEV);
                }
                let ifreq_ptr = LinuxUserspaceArg::<*mut Ifreq>::new(arg, self.get_process());
                let mac = crate::net::current_mac_address();
                let mut result = Ifreq {
                    ifr_name: [0; 16],
                    ifr_data: [0; 16],
                };
                let [lo, hi] = ARPHRD_ETHER.to_le_bytes();
                result.ifr_data[0] = lo;
                result.ifr_data[1] = hi;
                result.ifr_data[2..8].copy_from_slice(&mac.as_bytes());
                ifreq_ptr.write_slice(&[result])?;
                Ok(0)
            }
            #[cfg(feature = "udp")]
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket
                if op == SIOCSIFADDR =>
            {
                let ifreq_ptr = LinuxUserspaceArg::<*const Ifreq>::new(arg, self.get_process());
                let ifreq = ifreq_ptr.validate_ptr()?;
                let ip = core::net::Ipv4Addr::new(
                    ifreq.ifr_data[4],
                    ifreq.ifr_data[5],
                    ifreq.ifr_data[6],
                    ifreq.ifr_data[7],
                );
                crate::net::set_ip_addr(ip);
                Ok(0)
            }
            FileDescriptor::Tty(ref device) if op == TCGETS => {
                let ptr = LinuxUserspaceArg::<*mut termios>::new(arg, self.get_process());
                let current = device.lock().get_termios();
                ptr.write_slice(&[current])?;
                Ok(0)
            }
            FileDescriptor::Tty(ref device) if op == TCSETS || op == TCSETSW || op == TCSETSF => {
                let ptr = LinuxUserspaceArg::<*const termios>::new(arg, self.get_process());
                let new_settings = ptr.validate_ptr()?;
                device.lock().set_termios(new_settings);
                Ok(0)
            }
            FileDescriptor::Tty(ref device) if op == TIOCGPGRP => {
                let pgid = device.lock().fg_pgid();
                let ptr = LinuxUserspaceArg::<*mut c_int>::new(arg, self.get_process());
                let pgid_val = c_int::try_from(pgid.as_isize()).expect("pgid fits in c_int");
                ptr.write_slice(&[pgid_val])?;
                Ok(0)
            }
            FileDescriptor::Tty(ref device) if op == TIOCSPGRP => {
                let ptr = LinuxUserspaceArg::<*const c_int>::new(arg, self.get_process());
                let pgid_val = ptr.validate_ptr()?;
                let new_pgid = Tid::new(u64::try_from(pgid_val)?);
                let caller_pgid = self.current_process.lock().pgid();
                let signal_to_forward = {
                    let mut dev = device.lock();
                    let sig = dev.take_signal_for_new_fg(caller_pgid);
                    dev.set_fg_pgid(new_pgid);
                    sig
                };
                if let Some(sig) = signal_to_forward {
                    process_table::THE.with_lock(|mut pt| {
                        pt.send_signal_to_pgid(new_pgid, sig);
                    });
                }
                Ok(0)
            }
            _ => Err(Errno::EINVAL),
        }
    }
}
