use std::{
    env,
    error::Error,
    fmt::Write as _,
    io::Write as _,
    process::{Command, Stdio},
};

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=qemu.ld");
    println!("cargo:rerun-if-changed=../userspace/");
    println!("cargo:rerun-if-changed=../common/");
    println!("cargo:rerun-if-changed=../flake.nix");
    println!("cargo:rerun-if-changed=../flake.lock");
    println!("cargo:rerun-if-changed=../disk/bin/");
    println!("cargo::rustc-check-cfg=cfg(kani)");
    // For unit tests (which produce a binary from this library crate)
    println!("cargo:rustc-link-arg=-Tkernel/qemu.ld");

    if is_miri_execution() || is_kani_execution() {
        return Ok(());
    }

    generate_userspace_programs_include()?;

    Ok(())
}

fn is_miri_execution() -> bool {
    env::var_os("CARGO_CFG_MIRI").is_some()
}

fn is_kani_execution() -> bool {
    env::var_os("CARGO_CFG_KANI").is_some()
}

fn generate_userspace_programs_include() -> Result<(), Box<dyn Error>> {
    const USERSPACE_PROGRAMS_PATH: &str = "../kernel/src/autogenerated/userspace_programs.rs";

    let mut content = String::new();

    // Only embed prog1 for unit tests
    let prog1_path = std::fs::canonicalize("../disk/bin/prog1");
    if let Ok(path) = prog1_path {
        writeln!(
            content,
            "#[cfg(test)]\nuse common::include_bytes_align_as;\n\n#[cfg(test)]\npub static PROG1: &[u8] = include_bytes_align_as!(u64, \"{}\");",
            path.to_string_lossy()
        )?;
    }

    // Format in memory, then only write if content changed — preserves mtime to avoid rebuilds
    let mut rustfmt = Command::new("rustfmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()?;
    rustfmt
        .stdin
        .take()
        .unwrap()
        .write_all(content.as_bytes())?;
    let formatted = String::from_utf8(rustfmt.wait_with_output()?.stdout)?;

    let existing = std::fs::read_to_string(USERSPACE_PROGRAMS_PATH).unwrap_or_default();
    if existing == formatted {
        return Ok(());
    }

    std::fs::write(USERSPACE_PROGRAMS_PATH, &formatted)?;

    Ok(())
}
