[profile.default]
slow-timeout = { period = "10s", terminate-after = 2 }

[[profile.default.overrides]]
filter = "test(doom_starts)"
slow-timeout = { period = "20s", terminate-after = 1 }

[profile.deadlock-hunt]
slow-timeout = { period = "3600s", terminate-after = 1 }
test-threads = 1
