//! Thin shim: copy bindgen outputs generated by CMake (via
//! tools/bindgen-driver) into cargo's OUT_DIR, so `include!(concat!(env!
//! ("OUT_DIR"), "/X.rs"))` calls in src/lib.rs keep working.
//!
//! The real bindgen logic lives in tools/bindgen-driver and runs once per
//! CMake configure/build via the `headers-generated` custom target.

use std::{env, fs, path::Path};

const GENERATED: &[&str] = &[
    "syscalls.rs",
    "syscall_types.rs",
    "errno.rs",
    "socket_types.rs",
    "fs_types.rs",
    "sysinfo_types.rs",
];

fn main() {
    println!("cargo:rerun-if-env-changed=SOLAYA_HEADERS_GENERATED");

    let src_dir = env::var("SOLAYA_HEADERS_GENERATED").unwrap_or_else(|_| {
        panic!(
            "SOLAYA_HEADERS_GENERATED must be set. Build via \
             `make build` or `cmake --build build --target solaya-bin`; \
             the headers crate needs files produced by tools/bindgen-driver \
             and cargo on its own does not run it."
        )
    });
    let out_dir = env::var("OUT_DIR").unwrap();
    let src = Path::new(&src_dir);
    let out = Path::new(&out_dir);

    for name in GENERATED {
        let from = src.join(name);
        let to = out.join(name);
        println!("cargo:rerun-if-changed={}", from.display());
        fs::copy(&from, &to).unwrap_or_else(|e| {
            panic!(
                "copying {} -> {}: {}. Did you run \
                 `cmake --build build --target headers-generated`?",
                from.display(),
                to.display(),
                e
            )
        });
    }
}
