//! Thin shim: copy bindgen outputs generated by CMake (via
//! tools/bindgen-driver) into cargo's OUT_DIR, so `include!(concat!(env!
//! ("OUT_DIR"), "/X.rs"))` calls in src/lib.rs keep working.
//!
//! The real bindgen logic lives in tools/bindgen-driver and runs once per
//! CMake configure/build via the `headers-generated` custom target. The
//! source path is hardcoded relative to this crate's manifest dir
//! (`<repo>/build/headers/generated`) — matching the `binaryDir` pinned
//! by CMakePresets.json — so bare `cargo check` / rust-analyzer keep
//! working as long as a prior CMake build populated the files.

use std::{env, fs, path::Path};

const GENERATED: &[&str] = &[
    "syscalls.rs",
    "syscall_types.rs",
    "errno.rs",
    "socket_types.rs",
    "fs_types.rs",
    "sysinfo_types.rs",
];

fn main() {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let src = Path::new(manifest).join("../../build/headers/generated");
    let out_dir = env::var("OUT_DIR").unwrap();
    let out = Path::new(&out_dir);

    for name in GENERATED {
        let from = src.join(name);
        let to = out.join(name);
        println!("cargo:rerun-if-changed={}", from.display());
        fs::copy(&from, &to).unwrap_or_else(|e| {
            panic!(
                "copying {} -> {}: {}. Did you run \
                 `cmake --build build --target headers-generated`?",
                from.display(),
                to.display(),
                e
            )
        });
    }
}
