// Generated by build.rs from SOLAYA_USERSPACE_ARTIFACT_DIR.  Only needed
// by kernel unit tests that load fixture ELFs (INIT, PROG1); release
// builds read binaries from the VFS after initramfs extraction.
#[cfg(test)]
pub mod userspace_programs;
