//! The OS. Processes, memory management integration, filesystems, networking,
//! device drivers, syscalls, and trap handling.
//!
//! Layering invariant: may depend on `console`, `mm`, `hal`, `klib`, `abi`,
//! `headers`. May not contain raw CSR access, raw MMIO, or log-macro
//! definitions — those live in `hal` and `console`.
#![cfg_attr(not(miri), no_std)]
#![cfg_attr(not(miri), no_main)]
// Under miri several HAL entry points (CalleeSavedRegs::with_context, SBI
// calls, CSR reads) are stubs that panic; their transitive callees are
// provably unreachable in that cfg only. The workspace denies dead_code
// on the real riscv64 target and on kernel --tests, so we accept this
// narrow allow rather than cfg-gate every backtrace/reset helper.
#![cfg_attr(miri, allow(dead_code))]
#![cfg_attr(miri, allow(unused_imports))]
#![cfg_attr(miri, allow(unused_macros))]
#![cfg_attr(test, allow(unused_imports))]
#![cfg_attr(not(test), forbid(unsafe_code))]
#![cfg_attr(test, deny(unsafe_code))]
#![deny(clippy::unwrap_used)]
#![deny(clippy::ptr_as_ptr)]
#![deny(clippy::redundant_else)]
#![deny(clippy::manual_assert)]
#![deny(clippy::large_stack_arrays)]
#![deny(clippy::cast_sign_loss)]
#![feature(nonzero_ops)]
#![feature(custom_test_frameworks)]
#![feature(map_try_insert)]
#![feature(new_range_api)]
#![feature(ptr_metadata)]
#![feature(ptr_mask)]
#![feature(macro_metavar_expr_concat)]
#![feature(str_from_raw_parts)]
#![feature(macro_metavar_expr)]
#![feature(string_from_utf8_lossy_owned)]
#![feature(debug_closure_helpers)]
#![test_runner(test::test_runner)]
#![reexport_test_harness_main = "test_main"]

use crate::{
    interrupts::plic, io::uart::CONSOLE_UART, memory::page_tables, pci::enumerate_devices,
    processes::timer,
};
use alloc::vec::Vec;
use asm::wfi_loop;
use cpu::Cpu;
use debugging::{backtrace, symbols};
use device_tree::get_devicetree_range;
use memory::page_tables::MappingDescription;
use processes::process_table;

pub mod asm;
mod assert;
mod autogenerated;
mod byte_interpretable;
mod cpu;
mod debugging;
mod device_tree;
mod drivers;
mod fs;
mod init;
pub mod interrupts;
mod io;
mod memory;
mod net;
#[cfg(not(miri))]
pub mod panic;
mod pci;
mod platform;
mod processes;
mod syscalls;

mod test;

pub use console::{debug, info, print, println, warn};

// When running unit tests, the kernel is compiled as a standalone binary (not via
// boot crate). Assembly in sys references these symbols by name.
#[cfg(test)]
mod test_entry_points {
    #![allow(unsafe_code)]
    #[unsafe(no_mangle)]
    extern "C" fn kernel_init(hart_id: usize, dt: *const ()) -> ! {
        crate::kernel_init(hart_id, dt)
    }
    #[unsafe(no_mangle)]
    extern "C" fn prepare_for_scheduling() -> ! {
        crate::prepare_for_scheduling()
    }
    #[unsafe(no_mangle)]
    extern "C" fn handle_trap() {
        crate::interrupts::trap::handle_trap()
    }
    #[unsafe(no_mangle)]
    extern "C" fn get_process_satp_value() -> usize {
        crate::interrupts::trap::get_process_satp_value()
    }
    #[unsafe(no_mangle)]
    fn asm_panic_rust() {
        hal::cpu::asm_panic_rust()
    }
}

#[macro_use]
extern crate alloc;

pub extern "C" fn kernel_init(hart_id: usize, device_tree_pointer: *const ()) -> ! {
    let boot_cpu_id = cpu::CpuId::from_hart_id(hart_id);
    hal::per_cpu::STARTING_CPU_ID.initialize(boot_cpu_id);

    CONSOLE_UART.lock().init();

    info!("Hello World from Solaya!\n");
    info!("Device Tree Pointer: {:p}", device_tree_pointer);

    let version = hal::sbi::extensions::base_extension::sbi_get_spec_version();
    info!("SBI version {}.{}", version.major, version.minor);
    assert!(
        (version.major == 0 && version.minor >= 2) || version.major > 0,
        "Supported SBI Versions >= 0.2"
    );

    let num_cpus = hal::sbi::extensions::hart_state_extension::get_number_of_harts();
    info!("Number of Cores: {num_cpus}");

    symbols::init();
    device_tree::init(device_tree_pointer);

    // Switch the UART off the compile-time default and onto whatever the
    // device tree advertises. No-op on QEMU virt and the JH7110, which
    // both use 0x1000_0000; required for any future board that doesn't.
    if let Some(serial_reg) = device_tree::THE
        .root_node()
        .find_node("serial")
        .and_then(|node| node.parse_reg_property())
    {
        console::uart::bind(serial_reg.address);
    }

    let device_tree_range = get_devicetree_range();

    memory::init_page_allocator(&[device_tree_range]);

    backtrace::init();
    plic::discover_from_device_tree(boot_cpu_id);
    processes::timer::init();

    #[cfg(test)]
    test_main();

    let pci_information = pci::parse();

    let mut runtime_mapping = Vec::new();

    if let Some(ref pci_info) = pci_information {
        if let Some(pci_space_64_bit) =
            pci_info.get_first_range_for_type(pci::PCIBitField::MEMORY_SPACE_64_BIT_CODE)
        {
            let mut pci_allocator = pci::PCI_ALLOCATOR_64_BIT.lock();
            pci_allocator.init(pci_space_64_bit);
        }

        if let Some(pci_space_32_bit) =
            pci_info.get_first_range_for_type(pci::PCIBitField::MEMORY_SPACE_32_BIT_CODE)
        {
            let mut pci_allocator = pci::PCI_ALLOCATOR_32_BIT.lock();
            pci_allocator.init(pci_space_32_bit);
        }

        runtime_mapping.push(MappingDescription {
            virtual_address_start: memory::VirtAddr::new(
                pci_info.pci_host_bridge_address.as_usize(),
            ),
            size: pci_info.pci_host_bridge_length,
            privileges: page_tables::XWRMode::ReadWrite,
            name: "PCI Space",
        });

        for range in &pci_info.ranges {
            runtime_mapping.push(MappingDescription {
                virtual_address_start: memory::VirtAddr::new(range.cpu_address.as_usize()),
                size: range.size,
                privileges: page_tables::XWRMode::ReadWrite,
                name: "PCI Range",
            });
        }
    }

    memory::initialize_runtime_mappings(&runtime_mapping);

    io::tty_device::CONSOLE_TTY.initialize(alloc::sync::Arc::new(hal::spinlock::Spinlock::new(
        io::tty_device::TtyDeviceInner::new(),
    )));

    process_table::init();
    processes::syscall_runner::install();
    fs::init();
    io::uart::register_console_char_device();

    hal::cpu::write_sscratch(Cpu::init(boot_cpu_id, num_cpus) as usize);

    Cpu::current().activate_kernel_page_table();

    plic::init_plic();

    // Read UART interrupt number from device tree instead of hardcoded IRQ 10
    let uart_irq = device_tree::THE
        .root_node()
        .find_node("serial")
        .and_then(|node| node.get_property("interrupts"))
        .and_then(|mut p| p.consume_sized_type::<klib::big_endian::BigEndian<u32>>())
        .map(|be| be.get())
        .unwrap_or(10);
    // UART lives forever; leak the registration so it stays alive.
    core::mem::forget(plic::register(
        uart_irq,
        alloc::sync::Arc::new(io::uart::UartIrqHandler),
    ));

    driver_api::net_notifier::set_notifier(net::notify_packet_arrival);

    platform::init_from_device_tree();

    if let Some(ref pci_info) = pci_information {
        let pci_devices = enumerate_devices(pci_info);
        drivers::init_all_pci_devices(pci_devices);
    }

    drivers::init_all_dt_devices();

    init::bring_up_system();

    processes::kernel_tasks::create_worker_thread();

    info!("kernel_init done! Starting other harts");

    start_other_harts(hart_id, num_cpus);

    prepare_for_scheduling();
}

pub extern "C" fn prepare_for_scheduling() -> ! {
    // Enable all interrupts
    hal::cpu::write_sie(usize::MAX);

    // Enable global interrupts
    hal::cpu::csrs_sstatus(0b10);

    timer::set_timer(0);

    wfi_loop();
}

/// Returns whether the device tree advertises supervisor mode for `hart_id`.
///
/// On the StarFive JH7110 the SBI hart count includes the S7 monitor core
/// (hart 0), which has no S-mode and no MMU. Trying to start it from a
/// supervisor-mode kernel is undefined behavior. Filter by `riscv,isa`
/// containing `s` to skip such harts.
///
/// Permissive on missing data: any failure to locate `/cpus`, the `reg`
/// property, or `riscv,isa` returns `true` so the hart is started anyway.
/// We only skip on positive evidence that S-mode is absent.
fn hart_has_supervisor(hart_id: usize) -> bool {
    let Some(cpus_node) = device_tree::THE.root_node().find_node("cpus") else {
        return true;
    };
    for cpu in cpus_node.children() {
        let Some(mut reg) = cpu.get_property("reg") else {
            continue;
        };
        let Some(reg_val) = reg.consume_sized_type::<klib::big_endian::BigEndian<u32>>() else {
            continue;
        };
        if reg_val.get() as usize != hart_id {
            continue;
        }
        let Some(mut isa) = cpu.get_property("riscv,isa") else {
            return true;
        };
        let Some(isa_str) = isa.consume_str() else {
            return true;
        };
        return hal::isa::IsaExtensions::parse(isa_str).is_some_and(|i| i.has_supervisor());
    }
    true
}

fn start_other_harts(current_hart_id: usize, number_of_cpus: usize) {
    for hart_id in 0..number_of_cpus {
        if hart_id == current_hart_id {
            continue;
        }
        if !hart_has_supervisor(hart_id) {
            info!("Skipping hart {hart_id}: no supervisor mode");
            continue;
        }

        let cpu_struct = Cpu::init(cpu::CpuId::from_hart_id(hart_id), number_of_cpus);
        hal::sbi::extensions::hart_state_extension::start_hart(
            hart_id,
            hal::linker_symbols::start_hart_addr(),
            cpu_struct as usize,
        )
        .assert_success();
    }
}
