# cmake/llvm_tools.cmake — discover distro LLVM (>= 18) as bare command names.
#
# Why not find_program(): find_program caches an absolute path into
# CMakeCache.txt and bakes it into build.ninja.  When the same build/ dir is
# shared between a podman container and the host, the absolute path from one
# side ('/root/.cargo/bin/…' etc.) isn't executable on the other, and ninja
# fails with exit 126.  Commits ed010412 / dd5c89b0 / 490c0845 worked around
# this for cargo by emitting the bare command name instead.  We apply the
# same pattern to clang/lld/llvm-* here.
#
# We only use the discovered names to:
#   1. Verify at configure time that a compatible LLVM is installed (fail
#      fast with a clear message).
#   2. Bake the chosen bare names (e.g. `clang-18`, `llvm-objcopy`) into
#      wrapper scripts generated by cmake/clang_wrapper.cmake.
# build.ninja itself only sees wrapper-script paths under the build dir.

set(SOLAYA_LLVM_MIN_MAJOR 18 CACHE STRING
    "Minimum acceptable LLVM major version for distro tools."
)

# For each candidate name, try running `<name> --version` and parse the first
# x.y.z triple from the output.  Accept the first candidate whose major
# version is >= required_major.  Candidates are tried high-to-low so a host
# with multiple versions installed picks the newest compatible one.
function(solaya_find_llvm_tool out_var base required_major)
    # Probe order: versioned modern-to-legacy, then unversioned.  Covers
    # Debian/Ubuntu (clang-18), Arch/Fedora (plain clang), and anyone who
    # installs a newer LLVM side-by-side.
    set(_candidates "")
    foreach(_ver RANGE 25 ${required_major} -1)
        list(APPEND _candidates "${base}-${_ver}")
    endforeach()
    list(APPEND _candidates "${base}")

    foreach(_tool IN LISTS _candidates)
        execute_process(
            COMMAND ${_tool} --version
            OUTPUT_VARIABLE _out
            ERROR_QUIET
            RESULT_VARIABLE _rc
        )
        if(NOT _rc EQUAL 0)
            continue()
        endif()
        if(_out MATCHES "([0-9]+)\\.[0-9]+\\.[0-9]+")
            if(CMAKE_MATCH_1 GREATER_EQUAL required_major)
                set(${out_var} "${_tool}" PARENT_SCOPE)
                message(STATUS
                    "Found ${base} (LLVM ${CMAKE_MATCH_1}): ${_tool}")
                return()
            endif()
        endif()
    endforeach()

    message(FATAL_ERROR
        "${base} >= ${required_major} not found on PATH.  Install LLVM "
        "${required_major}+ (Ubuntu/Debian: `apt install clang-${required_major} "
        "lld-${required_major} llvm-${required_major}`; Fedora: `dnf install "
        "clang lld llvm`; Arch: `pacman -S clang lld llvm`)."
    )
endfunction()

solaya_find_llvm_tool(SOLAYA_CLANG          clang          ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_CLANGXX        clang++        ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLD            ld.lld         ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_AR        llvm-ar        ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_NM        llvm-nm        ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_OBJCOPY   llvm-objcopy   ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_OBJDUMP   llvm-objdump   ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_RANLIB    llvm-ranlib    ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_STRIP     llvm-strip     ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_READELF   llvm-readelf   ${SOLAYA_LLVM_MIN_MAJOR})
solaya_find_llvm_tool(SOLAYA_LLVM_ADDR2LINE llvm-addr2line ${SOLAYA_LLVM_MIN_MAJOR})
