#![cfg_attr(all(target_arch = "riscv64", not(miri)), no_std)]
#![cfg_attr(all(target_arch = "riscv64", not(miri)), no_main)]
#![cfg_attr(not(target_arch = "riscv64"), allow(dead_code))]
#![cfg_attr(not(target_arch = "riscv64"), allow(unused_imports))]
#![cfg_attr(not(target_arch = "riscv64"), allow(unused_macros))]
#![cfg_attr(miri, allow(dead_code))]
#![cfg_attr(miri, allow(unused_imports))]
#![cfg_attr(miri, allow(unused_macros))]
#![cfg_attr(kani, feature(maybe_uninit_slice))]
#![cfg_attr(test, allow(dead_code))]
#![cfg_attr(test, allow(unused_imports))]
#![cfg_attr(not(test), forbid(unsafe_code))]
#![cfg_attr(test, deny(unsafe_code))]
#![deny(clippy::unwrap_used)]
#![deny(clippy::ptr_as_ptr)]
#![deny(clippy::redundant_else)]
#![deny(clippy::manual_assert)]
#![deny(clippy::large_stack_arrays)]
#![deny(clippy::cast_sign_loss)]
#![feature(nonzero_ops)]
#![feature(custom_test_frameworks)]
#![feature(map_try_insert)]
#![feature(new_range_api)]
#![feature(ptr_metadata)]
#![feature(ptr_mask)]
#![feature(macro_metavar_expr_concat)]
#![feature(str_from_raw_parts)]
#![feature(macro_metavar_expr)]
#![feature(string_from_utf8_lossy_owned)]
#![feature(debug_closure_helpers)]
#![test_runner(test::test_runner)]
#![reexport_test_harness_main = "test_main"]

#[cfg(target_arch = "riscv64")]
use crate::{
    interrupts::plic, io::uart::CONSOLE_UART, memory::page_tables, pci::enumerate_devices,
    processes::timer,
};
#[cfg(target_arch = "riscv64")]
use alloc::vec::Vec;
#[cfg(target_arch = "riscv64")]
use asm::wfi_loop;
#[cfg(target_arch = "riscv64")]
use cpu::Cpu;
#[cfg(target_arch = "riscv64")]
use debugging::{backtrace, symbols};
#[cfg(target_arch = "riscv64")]
use device_tree::get_devicetree_range;
#[cfg(target_arch = "riscv64")]
use memory::page_tables::MappingDescription;
#[cfg(target_arch = "riscv64")]
use processes::process_table;

#[cfg(target_arch = "riscv64")]
pub mod asm;
mod assert;
#[cfg(target_arch = "riscv64")]
mod autogenerated;
#[cfg(target_arch = "riscv64")]
mod cpu;
#[cfg(target_arch = "riscv64")]
mod debugging;
mod device_tree;
#[cfg(target_arch = "riscv64")]
mod drivers;
mod fs;
#[cfg(target_arch = "riscv64")]
pub mod interrupts;
mod io;
mod klibc;
mod logging;
mod memory;
#[cfg(target_arch = "riscv64")]
mod net;
#[cfg(all(target_arch = "riscv64", not(miri)))]
pub mod panic;
mod pci;
#[cfg(target_arch = "riscv64")]
mod processes;
#[cfg(target_arch = "riscv64")]
mod syscalls;

mod test;

// When running unit tests, the kernel is compiled as a standalone binary (not via
// boot crate). Assembly in sys references these symbols by name.
#[cfg(test)]
mod test_entry_points {
    #![allow(unsafe_code)]
    #[unsafe(no_mangle)]
    extern "C" fn kernel_init(hart_id: usize, dt: *const ()) -> ! {
        crate::kernel_init(hart_id, dt)
    }
    #[unsafe(no_mangle)]
    extern "C" fn prepare_for_scheduling() -> ! {
        crate::prepare_for_scheduling()
    }
    #[unsafe(no_mangle)]
    extern "C" fn handle_trap() {
        crate::interrupts::trap::handle_trap()
    }
    #[unsafe(no_mangle)]
    extern "C" fn get_process_satp_value() -> usize {
        crate::interrupts::trap::get_process_satp_value()
    }
    #[unsafe(no_mangle)]
    fn asm_panic_rust() {
        arch::cpu::asm_panic_rust()
    }
}

#[macro_use]
extern crate alloc;

#[cfg(target_arch = "riscv64")]
pub extern "C" fn kernel_init(hart_id: usize, device_tree_pointer: *const ()) -> ! {
    let boot_cpu_id = cpu::CpuId::from_hart_id(hart_id);
    sys::cpu::STARTING_CPU_ID.initialize(boot_cpu_id);

    CONSOLE_UART.lock().init();

    info!("Hello World from Solaya!\n");
    info!("Device Tree Pointer: {:p}", device_tree_pointer);

    let version = arch::sbi::extensions::base_extension::sbi_get_spec_version();
    info!("SBI version {}.{}", version.major, version.minor);
    assert!(
        (version.major == 0 && version.minor >= 2) || version.major > 0,
        "Supported SBI Versions >= 0.2"
    );

    let num_cpus = arch::sbi::extensions::hart_state_extension::get_number_of_harts();
    info!("Number of Cores: {num_cpus}");

    symbols::init();
    device_tree::init(device_tree_pointer);
    let device_tree_range = get_devicetree_range();

    memory::init_page_allocator(&[device_tree_range]);

    backtrace::init();
    plic::discover_from_device_tree(boot_cpu_id);
    processes::timer::init();

    #[cfg(test)]
    test_main();

    let pci_information = pci::parse();

    let mut runtime_mapping = Vec::new();

    if let Some(ref pci_info) = pci_information {
        {
            let pci_space_64_bit = pci_info
                .get_first_range_for_type(pci::PCIBitField::MEMORY_SPACE_64_BIT_CODE)
                .expect("There must be a 64 bit allocation space.");
            let mut pci_allocator = pci::PCI_ALLOCATOR_64_BIT.lock();
            pci_allocator.init(pci_space_64_bit);
        }

        if let Some(pci_space_32_bit) =
            pci_info.get_first_range_for_type(pci::PCIBitField::MEMORY_SPACE_32_BIT_CODE)
        {
            let mut pci_allocator = pci::PCI_ALLOCATOR_32_BIT.lock();
            pci_allocator.init(pci_space_32_bit);
        }

        runtime_mapping.push(MappingDescription {
            virtual_address_start: memory::VirtAddr::new(
                pci_info.pci_host_bridge_address.as_usize(),
            ),
            size: pci_info.pci_host_bridge_length,
            privileges: page_tables::XWRMode::ReadWrite,
            name: "PCI Space",
            is_device: true,
        });

        for range in &pci_info.ranges {
            runtime_mapping.push(MappingDescription {
                virtual_address_start: memory::VirtAddr::new(range.cpu_address.as_usize()),
                size: range.size,
                privileges: page_tables::XWRMode::ReadWrite,
                name: "PCI Range",
                is_device: true,
            });
        }
    } else {
        info!("No PCI host bridge found in device tree, skipping PCI init");
    }

    memory::initialize_runtime_mappings(&runtime_mapping);

    io::tty_device::CONSOLE_TTY.initialize(alloc::sync::Arc::new(klibc::Spinlock::new(
        io::tty_device::TtyDeviceInner::new(),
    )));

    process_table::init();
    fs::init();

    arch::cpu::write_sscratch(Cpu::init(boot_cpu_id, num_cpus) as usize);

    Cpu::current().activate_kernel_page_table();

    plic::init_plic();

    if let Some(serial_node) = device_tree::THE.root_node().find_node("serial")
        && let Some(mut irq_prop) = serial_node.get_property("interrupts")
    {
        let irq = irq_prop
            .consume_sized_type::<klibc::big_endian::BigEndian<u32>>()
            .expect("UART interrupts property must be a u32")
            .get();
        plic::register_interrupt(irq, io::uart::on_uart_interrupt);
    }

    if let Some(ref pci_info) = pci_information {
        let pci_devices = enumerate_devices(pci_info);
        drivers::init_all_pci_devices(pci_devices);
    }

    // Initialize platform devices discovered from the device tree
    drivers::init_dwmac_devices();

    processes::kernel_tasks::create_worker_thread();

    info!("kernel_init done! Starting other harts");

    start_other_harts(hart_id, num_cpus);

    prepare_for_scheduling();
}

#[cfg(target_arch = "riscv64")]
pub extern "C" fn prepare_for_scheduling() -> ! {
    // Enable all interrupts
    arch::cpu::write_sie(usize::MAX);

    // Enable global interrupts
    arch::cpu::csrs_sstatus(0b10);

    timer::set_timer(0);

    wfi_loop();
}

#[cfg(target_arch = "riscv64")]
fn start_other_harts(current_hart_id: usize, number_of_cpus: usize) {
    use arch::sbi::extensions::hart_state_extension;
    use klibc::big_endian::BigEndian;

    let root = device_tree::THE.root_node();
    let cpus_node = root
        .find_node("cpus")
        .expect("Device tree must have a cpus node");

    for cpu_node in cpus_node.children() {
        if !cpu_node.name.starts_with("cpu@") {
            continue;
        }

        // Skip harts marked as disabled in the device tree
        if let Some(mut status) = cpu_node.get_property("status")
            && let Some(status_str) = status.consume_str()
            && status_str != "okay"
        {
            info!("Skipping hart {} (status: {status_str})", cpu_node.name);
            continue;
        }

        // Skip harts without supervisor mode (e.g. SiFive S7 monitor core on JH7110)
        if let Some(mut isa_prop) = cpu_node.get_property("riscv,isa")
            && let Some(isa_str) = isa_prop.consume_str()
            && let Some(isa) = arch::isa::IsaExtensions::parse(isa_str)
            && !isa.has_supervisor()
        {
            info!("Skipping {} (no S-mode: {isa_str})", cpu_node.name);
            continue;
        }

        let Some(mut reg_prop) = cpu_node.get_property("reg") else {
            continue;
        };
        let hart_id = reg_prop
            .consume_sized_type::<BigEndian<u32>>()
            .expect("CPU reg must be a u32")
            .get() as usize;

        if hart_id == current_hart_id {
            continue;
        }

        if !hart_state_extension::is_hart_stopped(hart_id) {
            info!("Skipping hart {hart_id} (not in stopped state)");
            continue;
        }

        let cpu_struct = Cpu::init(cpu::CpuId::from_hart_id(hart_id), number_of_cpus);
        hart_state_extension::start_hart(
            hart_id,
            arch::linker_symbols::start_hart_addr(),
            cpu_struct as usize,
        )
        .assert_success();
    }
}

#[cfg(kani)]
fn main() {}
