name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix develop --command just build

      - name: Format check
        run: nix develop --command cargo fmt --check

      - name: Clippy
        run: nix develop --command just clippy

      - name: Unit tests
        run: nix develop --command just unit-test

      - name: Miri
        run: nix develop --command just miri

      - name: System tests
        run: nix develop --command just system-test

      - name: Kani
        run: nix develop --command just kani
